//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia
    {
        public int ID { get; set; }
        public string MaCode { get; set; }
        public int GiamTheoPhanTram { get; set; }
        public decimal GiamTheoSoTien { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayHetHan { get; set; }
    }
}
