//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public System.DateTime NgayThangNamSinh { get; set; }
        public string SoDienThoaiNhanVien { get; set; }
        public string EmailNhanVien { get; set; }
        public string SoTheCanCuocNhanVien { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string HinhDaiDienNhanVien { get; set; }
        public string QueQuan { get; set; }
    }
}
