//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyKho
    {
        public string TenSanPham { get; set; }
        public string MaSanPham { get; set; }
        public string DanhMucSanPham { get; set; }
        public Nullable<long> SoLuongTonKho { get; set; }
        public Nullable<long> GiaNhap { get; set; }
        public Nullable<long> GiaBan { get; set; }
    }
}
