//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyNhapHang
    {
        public string MaSanPham { get; set; }
        public Nullable<long> HangDangVe { get; set; }
        public string TrangThaiNhapHang { get; set; }
        public Nullable<long> NhapKho { get; set; }
        public Nullable<long> DonGia { get; set; }
    }
}
