//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyKho
    {
        public int MaKho { get; set; }
        public string TenKho { get; set; }
        public string DiaChiKho { get; set; }
        public Nullable<int> DienTichKho { get; set; }
        public int MaNhanVienQuanLy { get; set; }
        public int SucChuaHienTai { get; set; }
    }
}
