//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyBanHang
    {
        public int MaDonHang { get; set; }
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string SoDienThoaiKhachHang { get; set; }
    }
}
