//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyBanHang
    {
        public int MaDonHang { get; set; }
        public string TenKhachHang { get; set; }
        public decimal ThanhTien { get; set; }
        public System.DateTime NgayTaoDon { get; set; }
        public int MaTrangThaiDonHang { get; set; }
    
        public virtual ChiTietDonBanHang ChiTietDonBanHang { get; set; }
    }
}
